### ISSUE TITLE
Support invalid URLs

### ISSUE THREAD

**Issue by oskarrough** [internet4000/media-url-parser#6]
If you call `mediaUrlParser('youtu.be/yhRdMTQWhOc')` it will fail to parse it and throw an error. It doesn't throw because it can't find a provider or id but because it's not a valid URL.

I'd like to change the behaviour to parse it anyway and return provider etc.

At the moment radio4000-player will break down if it encounters an URL like "youtu.be/yhRdMTQWhOc". This is because we used to rely on `ytid`.

**Comment by oskarrough** [comment]
instead of throwing an error on invalid URL we can throw an error if we can't detect a provider.

**Comment by 4www** [comment]
if errors are not blocking for the ui, and the system is fail safe (in the case of r4 it skips to the next track), it's good
